-- ═══════════════════════════════════════════════════════════════════
-- Migration 005: Add WhatsApp & Nudge columns to profiles
-- ═══════════════════════════════════════════════════════════════════

-- 1. Add WhatsApp settings and pending nudges to profiles
alter table profiles
    add column if not exists whatsapp_enabled   boolean default false,
    add column if not exists whatsapp_phone     text,
    add column if not exists whatsapp_snapshots boolean default true,
    add column if not exists whatsapp_alerts    boolean default true,
    add column if not exists pending_nudges     text;

comment on column profiles.pending_nudges is 
    'Stores personalised career nudges generated by job_memory_insights(). '
    'Consumed and cleared by the next job_weekly_snapshots() run.';

-- 2. Create WhatsApp message log table
create table if not exists whatsapp_messages (
    id           uuid primary key default uuid_generate_v4(),
    user_id      uuid references auth.users(id) on delete set null,
    phone        text not null,
    message_type text, -- mentor, snapshot, alert, nudge
    body         text,
    twilio_sid   text,
    created_at   timestamptz default now()
);

-- Enable RLS (Service role only for insertions, but good practice)
alter table whatsapp_messages enable row level security;

-- Users can only see their own notification logs
create policy "whatsapp_messages_self" on whatsapp_messages
    for select using (user_id = auth.uid());

create index if not exists idx_whatsapp_messages_user on whatsapp_messages(user_id);
create index if not exists idx_profiles_whatsapp on profiles(whatsapp_enabled) where whatsapp_enabled = true;
